apiVersion: v2
name: raw
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.13.0"
description: "RAW Helm Chart"
type: application
home: https://github.com/Scalified/helm-raw
icon: https://scalified.github.io/helm-raw/icon.png
keywords:
  - raw
  - templates
  - resources
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/signKey: |
    fingerprint: 687D9BE990493C58C0CFBEB65A065879383D7E21
    url: https://keybase.io/scalified/pgp_keys.asc
